# Generated by Django 4.2.11 on 2024-09-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypAPI', '0002_difficultylevel_question_remove_gameplayer_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='definition',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
