# Generated by Django 4.2.11 on 2024-09-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypAPI', '0003_remove_question_definition_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
