# Generated by Django 4.2.11 on 2024-09-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypAPI', '0004_alter_question_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
